
const seed = window.SEED;
let user = JSON.parse(localStorage.getItem('aleman_user') || 'null');
if (!user) location.href = 'index.html';
let state = JSON.parse(localStorage.getItem('aleman_state') || 'null') || structuredClone(seed);

const $ = id => document.getElementById(id);
const fmt = n => (+n || 0).toLocaleString('en-US');
const today = () => new Date().toISOString().slice(0,10);
const esc = v => String(v ?? '').replace(/[&<>'"]/g, s => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[s]));
const save = () => { localStorage.setItem('aleman_state', JSON.stringify(state)); syncUser(); renderAll(); };
const avatarFor = name => 'data:image/svg+xml;utf8,' + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120"><rect width="120" height="120" rx="60" fill="%230878be"/><text x="50%" y="54%" dominant-baseline="middle" text-anchor="middle" font-family="Arial" font-size="42" font-weight="700" fill="white">${String(name||'U').trim().slice(0,2)}</text></svg>`);

function syncUser(){
  const fresh = state.employees.find(e => e.email === user.email) || state.employees.find(e => e.name === user.name);
  if(fresh){ user = {...user, ...fresh}; localStorage.setItem('aleman_user', JSON.stringify(user)); }
  const avatar = user.avatar || avatarFor(user.name);
  const chip = document.querySelector('.chip');
  if(chip){ chip.classList.add('profile-chip'); chip.innerHTML = `<img class="profile-avatar" src="${avatar}"><div class="profile-meta"><b>${esc(user.name)}</b><span>${esc(user.title||user.role||'')}</span></div><button class="btn secondary" onclick="profileModal()">بروفايل</button><button class="btn secondary" onclick="logout()">خروج</button>`; }
}
function allowed(p){ return (seed.permissions[user.role] || []).includes(p) || user.role === 'owner'; }
function isAdmin(){ return ['owner','general_manager'].includes(user.role); }
function badge(v){ let s=String(v||''); let c=/نشط|ساري|مدفوعة|حاضر|تم|active|معتمد|متوفر|مكتمل|تم التسليم/.test(s)?'ok':/متأخر|مرفوض|غياب|خصم|inactive|تحت الحد|ملغي/.test(s)?'danger':'warn'; return `<span class="badge ${c}">${esc(s||'جديد')}</span>`; }
function idFor(prefix, arr){ return prefix + '-' + Date.now().toString().slice(-6); }
function init(){ syncUser(); document.querySelectorAll('#nav button').forEach(b=>{ if(!allowed(b.dataset.page)) b.style.display='none'; }); renderAll(); showPage('dashboard'); }
function showPage(p){ if(!allowed(p)) p='dashboard'; document.querySelectorAll('.section').forEach(s=>s.classList.remove('active')); $('sec-'+p).classList.add('active'); document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p)); pageTitle.textContent=document.querySelector(`[data-page="${p}"]`)?.textContent||'لوحة التحكم'; pageHint.textContent = pageHints[p] || 'إدارة كاملة حسب الصلاحية'; }
const pageHints = {dashboard:'نظرة ذكية على التشغيل والتحصيل والمخزون',hr:'ملفات موظفين + صور شخصية + حضور ورواتب',accounts:'تحصيلات ومصروفات قابلة للتعديل والحذف',sales:'Pipeline ذكي للعملاء والمتابعات',customers:'كل عميل له تفاصيل وحالة ومتابعة',orders:'إدارة الطلبات والحالات والتسليم',delivery:'جدولة المناديب وإثبات التسليم',inventory:'حركة المخزون وحدود التنبيه',products:'المنتجات والأسعار والتصنيفات',pricing:'تحديث الأسعار وحفظ الحالة',invoices:'فواتير منسقة إبداعياً للطباعة',contracts:'عقود منسقة وقابلة للتعديل',complaints:'إدارة الشكاوى والمسؤول والحالة',reports:'تصدير تقارير Excel منسقة',settings:'إعدادات النظام والبيانات'};
function table(headers, rows){ return `<div class="table-wrap"><table><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr>${rows.join('')}</table></div><div class="mobile-cards">${rows.map(r=>`<div class="mcard">${r.replaceAll('<td>','<p>').replaceAll('</td>','</p>').replace(/<tr>|<\/tr>/g,'')}</div>`).join('')}</div>`; }
function actions(type,i,print=''){ return `<div class="row-actions"><button class="mini" onclick="editRecord('${type}',${i})">تعديل</button><button class="mini alt" onclick="viewRecord('${type}',${i})">تفاصيل</button>${print}<button class="mini danger" onclick="deleteRecord('${type}',${i})">حذف</button></div>`; }
function renderAll(){ renderDashboard();renderHR();renderAccounts();renderSales();renderCustomers();renderOrders();renderDelivery();renderInventory();renderProducts();renderPricing();renderInvoices();renderContracts();renderComplaints();renderReports();renderSettings(); }
function renderDashboard(){ let due=state.invoices.reduce((a,i)=>a+(+i.subtotal-(+i.paid||0)),0), low=state.products.filter(p=>+p.stock<=+p.min).length, open=state.complaints.filter(c=>c.status!=='مغلقة').length; $('content-dashboard').innerHTML=`<div class="smart-strip"><div><h2>مركز الإدارة الذكي</h2><p>كل البيانات قابلة للتعديل، حذف، تغيير حالة، وتصدير بتصميم منسق.</p></div><button class="btn gold" onclick="exportExcel('full')">تصدير شامل Excel</button></div><div class="grid"><div class="card kpi"><span>عملاء</span><strong>${state.customers.length}</strong></div><div class="card kpi"><span>طلبيات</span><strong>${state.orders.length}</strong></div><div class="card kpi"><span>منتجات تحت الحد</span><strong>${low}</strong></div><div class="card kpi"><span>مستحقات</span><strong>${fmt(due)}</strong></div></div><div class="grid2" style="margin-top:16px"><div class="card"><h2>تنبيهات ذكية</h2><p>• ${low} صنف يحتاج مراجعة مخزون.</p><p>• ${open} شكوى مفتوحة تحتاج متابعة.</p><p>• المستحقات الحالية: ${fmt(due)} جنيه.</p></div><div class="card mini-chart"><h2>مؤشرات الأداء</h2><p>المبيعات</p><div class="bar"><i style="width:76%"></i></div><p>التحصيل</p><div class="bar"><i style="width:58%"></i></div><p>التوصيل</p><div class="bar"><i style="width:82%"></i></div></div></div>`; }
function renderHR(){ let rows=state.employees.map((e,i)=>`<tr><td><img class="avatar-sm" src="${e.avatar||avatarFor(e.name)}"></td><td>${esc(e.code)}</td><td>${esc(e.name)}</td><td>${esc(e.title)}</td><td>${esc(e.dept)}</td><td>${esc(e.email)}</td><td>${fmt(e.salary)}</td><td>${badge(e.status)}</td><td>${actions('employees',i)}</td></tr>`); let att=state.attendance.map((a,i)=>`<tr><td>${a.date}</td><td>${esc(a.employee)}</td><td>${a.checkin}</td><td>${a.checkout}</td><td>${a.late} دقيقة</td><td>${a.overtime} دقيقة</td><td>${badge(a.status)}</td><td>${actions('attendance',i)}</td></tr>`); $('content-hr').innerHTML=`<div class="toolbar"><button class="btn" onclick="editRecord('employees')">إضافة موظف + صورة</button><button class="btn secondary" onclick="editRecord('attendance')">تسجيل حضور</button><button class="btn gold" onclick="payrollModal()">خصم/بدل</button><button class="btn secondary" onclick="exportExcel('employees')">Excel منسق</button></div><div class="card"><h2>الموظفين والرواتب</h2>${table(['صورة','كود','الاسم','الوظيفة','القسم','الإيميل','المرتب','الحالة','إجراءات'],rows)}</div><div class="card" style="margin-top:16px"><h2>الحضور والانصراف</h2>${table(['التاريخ','الموظف','حضور','انصراف','تأخير','إضافي','الحالة','إجراءات'],att)}</div>`; }
function renderAccounts(){ let totalInv=state.invoices.reduce((a,i)=>a+(+i.subtotal||0),0), paid=state.invoices.reduce((a,i)=>a+(+i.paid||0),0), exp=state.expenses.reduce((a,e)=>a+(+e.amount||0),0); let rec=state.receipts.map((r,i)=>`<tr><td>${r.id}</td><td>${r.date}</td><td>${esc(r.customer)}</td><td>${fmt(r.amount)}</td><td>${esc(r.method)}</td><td>${r.invoice}</td><td>${actions('receipts',i)}</td></tr>`); let ex=state.expenses.map((e,i)=>`<tr><td>${e.id}</td><td>${e.date}</td><td>${esc(e.category)}</td><td>${esc(e.desc)}</td><td>${fmt(e.amount)}</td><td>${badge(e.status)}</td><td>${actions('expenses',i)}</td></tr>`); $('content-accounts').innerHTML=`<div class="grid"><div class="card kpi"><span>إجمالي الفواتير</span><strong>${fmt(totalInv)}</strong></div><div class="card kpi"><span>محصل</span><strong>${fmt(paid)}</strong></div><div class="card kpi"><span>مصروفات</span><strong>${fmt(exp)}</strong></div><div class="card kpi"><span>رصيد تقديري</span><strong>${fmt(paid-exp)}</strong></div></div><div class="toolbar"><button class="btn" onclick="editRecord('receipts')">سند قبض</button><button class="btn gold" onclick="editRecord('expenses')">مصروف جديد</button><button class="btn secondary" onclick="exportExcel('accounts')">Excel منسق</button></div><div class="card"><h2>سندات القبض</h2>${table(['رقم','تاريخ','عميل','مبلغ','طريقة','فاتورة','إجراءات'],rec)}</div><div class="card" style="margin-top:16px"><h2>المصروفات والخزنة</h2>${table(['رقم','تاريخ','بند','الوصف','المبلغ','الحالة','إجراءات'],ex)}</div>`; }
function renderSales(){ const stages=['lead','follow-up','active','inactive']; $('content-sales').innerHTML=`<div class="grid">${stages.map(s=>`<div class="card kpi"><span>${s}</span><strong>${state.customers.filter(c=>c.status===s).length}</strong></div>`).join('')}</div><div class="kanban">${stages.map(s=>`<div class="lane"><h3>${s}</h3>${state.customers.filter(c=>c.status===s).slice(0,8).map(c=>`<div class="lead-card"><b>${esc(c.brand)}</b><span>${esc(c.sales||'بدون مسؤول')}</span><small>${esc(c.notes||'لا توجد ملاحظات')}</small></div>`).join('')}</div>`).join('')}</div>`; }
function renderCustomers(){ let rows=state.customers.map((c,i)=>`<tr><td>${i+1}</td><td>${esc(c.brand)}</td><td>${esc(c.phone)}</td><td>${esc(c.contact)}</td><td>${esc(c.location)}</td><td>${esc(c.sales)}</td><td>${badge(c.status)}</td><td>${esc(c.nextFollow||'')}</td><td>${esc(c.notes)}</td><td>${actions('customers',i)}</td></tr>`); $('content-customers').innerHTML=`<div class="toolbar"><button class="btn" onclick="editRecord('customers')">إضافة عميل</button><button class="btn secondary" onclick="exportExcel('customers')">Excel منسق</button></div>${table(['#','البراند','الهاتف','المسؤول','المنطقة','المبيعات','الحالة','متابعة قادمة','ملاحظات','إجراءات'],rows)}`; }
function renderOrders(){ let rows=state.orders.map((o,i)=>`<tr><td>${o.id}</td><td>${esc(o.customer)}</td><td>${o.date}</td><td>${esc(o.driver||'')}</td><td>${fmt(o.total)}</td><td>${badge(o.status)}</td><td>${actions('orders',i,`<button class="mini print" onclick="printInvoice('${o.id}')">فاتورة</button>`)}</td></tr>`); $('content-orders').innerHTML=`<div class="toolbar"><button class="btn" onclick="editRecord('orders')">طلب جديد</button><button class="btn secondary" onclick="exportExcel('orders')">Excel منسق</button></div>${table(['رقم','العميل','تاريخ التسليم','المندوب','الإجمالي','الحالة','إجراءات'],rows)}`; }
function renderDelivery(){ let rows=state.deliveries.map((d,i)=>`<tr><td>${d.id}</td><td>${d.order}</td><td>${esc(d.customer)}</td><td>${esc(d.driver)}</td><td>${d.date}</td><td>${badge(d.status)}</td><td>${esc(d.proof||'')}</td><td>${actions('deliveries',i)}</td></tr>`); $('content-delivery').innerHTML=`<div class="toolbar"><button class="btn" onclick="editRecord('deliveries')">جدولة توصيل</button></div>${table(['رقم','طلب','عميل','مندوب','موعد','الحالة','إثبات','إجراءات'],rows)}`; }
function renderInventory(){ let rows=state.products.map((p,i)=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>المخزن الرئيسي</td><td>${p.stock} ${p.unit}</td><td>${p.min}</td><td>${badge(p.stock<=p.min?'تحت الحد':'متوفر')}</td><td>${actions('products',i)}</td></tr>`); $('content-inventory').innerHTML=`<div class="toolbar"><button class="btn" onclick="stockModal()">حركة مخزن</button><button class="btn secondary" onclick="exportExcel('inventory')">Excel منسق</button></div>${table(['كود','الصنف','المخزن','الرصيد','حد التنبيه','الحالة','إجراءات'],rows)}`; }
function renderProducts(){ let rows=state.products.map((p,i)=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>${esc(p.category)}</td><td>${esc(p.unit)}</td><td>${fmt(p.price)}</td><td>${p.stock}</td><td>${badge(p.status||'نشط')}</td><td>${actions('products',i)}</td></tr>`); $('content-products').innerHTML=`<div class="toolbar"><button class="btn" onclick="editRecord('products')">إضافة منتج</button><button class="btn secondary" onclick="exportExcel('products')">Excel منسق</button></div>${table(['كود','الصنف','التصنيف','الوحدة','السعر','الرصيد','الحالة','إجراءات'],rows)}`; }
function renderPricing(){ renderProducts(); $('content-pricing').innerHTML=$('content-products').innerHTML+`<div class="card" style="margin-top:16px"><h2>سياسة التسعير</h2><p>أي تعديل في سعر المنتج يتم حفظه فوراً، ويمكن لاحقاً ربطه بجدول Price History في Supabase.</p></div>`; }
function renderInvoices(){ let rows=state.invoices.map((i,n)=>`<tr><td>${i.id}</td><td>${esc(i.customer)}</td><td>${i.date}</td><td>${i.due}</td><td>${fmt(i.subtotal)}</td><td>${fmt(i.paid)}</td><td>${fmt((+i.subtotal||0)-(+i.paid||0))}</td><td>${badge(i.status)}</td><td>${actions('invoices',n,`<button class="mini print" onclick="printInvoice(null,'${i.id}')">طباعة</button>`)}</td></tr>`); $('content-invoices').innerHTML=`<div class="toolbar"><button class="btn" onclick="editRecord('invoices')">فاتورة جديدة</button><button class="btn secondary" onclick="exportExcel('invoices')">Excel منسق</button></div>${table(['رقم','عميل','تاريخ','استحقاق','القيمة','مدفوع','متبقي','حالة','إجراءات'],rows)}`; }
function renderContracts(){ let rows=state.contracts.map((c,i)=>`<tr><td>${c.id}</td><td>${esc(c.customer)}</td><td>${c.start}</td><td>${c.end}</td><td>${badge(c.status)}</td><td>${esc(c.terms)}</td><td>${actions('contracts',i,`<button class="mini print" onclick="printContract('${c.id}')">طباعة</button>`)}</td></tr>`); $('content-contracts').innerHTML=`<div class="toolbar"><button class="btn" onclick="editRecord('contracts')">عقد جديد</button><button class="btn secondary" onclick="exportExcel('contracts')">Excel منسق</button></div>${table(['رقم','عميل','من','إلى','حالة','بنود','إجراءات'],rows)}`; }
function renderComplaints(){ let rows=state.complaints.map((c,i)=>`<tr><td>${c.id}</td><td>${esc(c.customer)}</td><td>${esc(c.title)}</td><td>${esc(c.owner)}</td><td>${badge(c.status)}</td><td>${esc(c.details)}</td><td>${actions('complaints',i)}</td></tr>`); $('content-complaints').innerHTML=`<div class="toolbar"><button class="btn" onclick="editRecord('complaints')">شكوى جديدة</button></div>${table(['رقم','عميل','الموضوع','المسؤول','الحالة','التفاصيل','إجراءات'],rows)}`; }
function renderReports(){ $('content-reports').innerHTML=`<div class="grid"><div class="card"><h2>تقرير شامل</h2><p>كل بيانات النظام في ملف Excel منسق.</p><button class="btn" onclick="exportExcel('full')">تصدير شامل</button></div><div class="card"><h2>تقرير عملاء</h2><button class="btn secondary" onclick="exportExcel('customers')">تصدير العملاء</button></div><div class="card"><h2>تقرير HR</h2><button class="btn secondary" onclick="exportExcel('employees')">تصدير الموظفين</button></div><div class="card"><h2>تقرير فواتير</h2><button class="btn secondary" onclick="exportExcel('invoices')">تصدير الفواتير</button></div></div>`; }
function renderSettings(){ $('content-settings').innerHTML=`<div class="card"><h2>إعدادات النظام</h2><p>النسخة الحالية LocalStorage. كل تعديل/حذف يتم حفظه في المتصفح. عند الربط بـ Supabase يمكن تحويل نفس الشاشات إلى قاعدة بيانات فعلية.</p><div class="toolbar"><button class="btn danger" onclick="resetData()">Reset للبيانات التجريبية</button><button class="btn secondary" onclick="exportExcel('full')">نسخة Excel احتياطية</button></div></div>`; }
function modal(t,h){ modalTitle.textContent=t; modalBody.innerHTML=h; $('modal').classList.add('show'); }
function closeModal(){ $('modal').classList.remove('show'); }
function field(id,label,type='text',val=''){ return `<label>${label}<input id="${id}" class="input" type="${type}" value="${esc(val)}"></label>`; }
function area(id,label,val=''){ return `<label>${label}<textarea id="${id}" class="input">${esc(val)}</textarea></label>`; }
function selectField(id,label,options,val=''){ return `<label>${label}<select id="${id}" class="input">${options.map(o=>`<option value="${esc(o)}" ${o==val?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`; }
const schemas={employees:[['name','الاسم'],['title','الوظيفة'],['dept','القسم'],['email','الإيميل'],['password','كلمة المرور'],['salary','المرتب','number'],['allowance','بدلات','number'],['deduction','خصومات','number'],['role','الصلاحية','select',['sales_rep','delivery_rep','accountant','warehouse_staff','storekeeper','sales_manager','accounts_manager','general_manager']],['status','الحالة','select',['نشط','موقوف','إجازة']]],attendance:[['date','التاريخ','date'],['employee','الموظف'],['checkin','حضور','time'],['checkout','انصراف','time'],['late','تأخير','number'],['overtime','إضافي','number'],['status','الحالة','select',['حاضر','غياب','إجازة','متأخر']]],customers:[['brand','البراند'],['phone','الهاتف'],['contact','المسؤول'],['location','المنطقة'],['sales','مسؤول المبيعات'],['status','الحالة','select',['lead','follow-up','active','inactive']],['nextFollow','متابعة قادمة','date'],['notes','ملاحظات','area']],products:[['name','الصنف'],['category','التصنيف'],['unit','الوحدة'],['price','السعر','number'],['stock','الرصيد','number'],['min','حد التنبيه','number'],['status','الحالة','select',['نشط','موقوف']]],orders:[['customer','العميل'],['date','تاريخ التسليم','date'],['driver','المندوب'],['total','الإجمالي','number'],['status','الحالة','select',['قيد التجهيز','جاهز','خرج للتوصيل','تم التسليم','ملغي']],['notes','ملاحظات','area']],deliveries:[['order','رقم الطلب'],['customer','العميل'],['driver','المندوب'],['date','الموعد'],['status','الحالة','select',['مجدول','في الطريق','تم التسليم','متأخر','ملغي']],['proof','إثبات التسليم']],invoices:[['customer','العميل'],['date','التاريخ','date'],['due','استحقاق','date'],['subtotal','القيمة','number'],['discount','خصم','number'],['tax','ضريبة','number'],['paid','مدفوع','number'],['status','الحالة','select',['غير مدفوعة','جزئي','مدفوعة','متأخرة']]],contracts:[['customer','العميل'],['start','من','date'],['end','إلى','date'],['status','الحالة','select',['مسودة','ساري','منتهي','ملغي']],['terms','بنود العقد','area']],complaints:[['customer','العميل'],['title','الموضوع'],['owner','المسؤول'],['status','الحالة','select',['مفتوحة','قيد الحل','مغلقة','متأخرة']],['details','التفاصيل','area']],receipts:[['date','التاريخ','date'],['customer','العميل'],['amount','المبلغ','number'],['method','طريقة الدفع'],['invoice','رقم الفاتورة']],expenses:[['date','التاريخ','date'],['category','البند'],['desc','الوصف'],['amount','المبلغ','number'],['status','الحالة','select',['مسودة','معتمد','مرفوض']]]};
function editRecord(type,index=null){ let arr=state[type], rec=index===null?{}:arr[index]; let schema=schemas[type]; let html=`<div class="form-grid">`; if(type==='employees') html+=`<label>الصورة الشخصية<input id="f_avatar" class="input" type="file" accept="image/*"></label>`; schema.forEach(f=>{let [k,l,t,opts]=f, v=rec[k]??(t==='date'?today():''); html += t==='area'?area('f_'+k,l,v):t==='select'?selectField('f_'+k,l,opts,v):field('f_'+k,l,t||'text',v);}); html+=`</div><br><button class="btn" onclick="saveRecord('${type}',${index===null?'null':index})">حفظ</button>`; modal(index===null?'إضافة بيانات':'تعديل البيانات', html); }
function saveRecord(type,index){ let obj=index===null?{}:{...state[type][index]}; (schemas[type]||[]).forEach(f=>{let [k,l,t]=f, el=$('f_'+k); obj[k]=t==='number'?+el.value:el.value;}); if(type==='employees' && !obj.code) obj.code='EMP-'+String(state.employees.length+1).padStart(3,'0'); if(type==='products' && !obj.id) obj.id='PRD-'+String(state.products.length+1).padStart(3,'0'); if(type==='orders' && !obj.id) obj.id=idFor('ORD',state.orders); if(type==='deliveries' && !obj.id) obj.id=idFor('DEL',state.deliveries); if(type==='invoices' && !obj.id) obj.id=idFor('INV',state.invoices); if(type==='contracts' && !obj.id) obj.id=idFor('CON',state.contracts); if(type==='complaints' && !obj.id) obj.id=idFor('CMP',state.complaints); if(type==='receipts' && !obj.id) obj.id=idFor('REC',state.receipts); if(type==='expenses' && !obj.id) obj.id=idFor('EXP',state.expenses); const file=$('f_avatar')?.files?.[0]; const commit=()=>{ if(index===null) state[type].unshift(obj); else state[type][index]=obj; closeModal(); save(); }; if(file){ const r=new FileReader(); r.onload=()=>{ obj.avatar=r.result; commit(); }; r.readAsDataURL(file); } else commit(); }
function viewRecord(type,index){ const rec=state[type][index]; modal('تفاصيل كاملة', `<div class="details-grid">${Object.entries(rec).map(([k,v])=>`<div><b>${esc(k)}</b><span>${typeof v==='object'?esc(JSON.stringify(v)):esc(v)}</span></div>`).join('')}</div>`); }
function deleteRecord(type,index){ if(confirm('تأكيد حذف هذا السجل نهائياً؟')){ state[type].splice(index,1); save(); } }
function payrollModal(){ modal('خصم أو بدل',`<div class="form-grid">${field('pEmp','اسم الموظف')}${field('pAllow','بدل إضافي','number','0')}${field('pDed','خصم','number','0')}</div><br><button class="btn" onclick="let e=state.employees.find(x=>x.name===pEmp.value)||state.employees[0];e.allowance=(+e.allowance||0)+(+pAllow.value||0);e.deduction=(+e.deduction||0)+(+pDed.value||0);closeModal();save()">تطبيق</button>`); }
function stockModal(){ modal('حركة مخزن',`<div class="form-grid">${field('sProduct','اسم الصنف')}${field('sQty','الكمية +/-','number')}</div><br><button class="btn" onclick="let p=state.products.find(x=>x.name===sProduct.value)||state.products[0];p.stock=(+p.stock||0)+(+sQty.value||0);closeModal();save()">تطبيق</button>`); }
function profileModal(){ const idx=state.employees.findIndex(e=>e.email===user.email); editRecord('employees', Math.max(idx,0)); }
function printHeader(title){ return `<div class="doc-head"><div><img class="paper-logo" src="assets/logo.png"><h1>${title}</h1><p>شركة الإيمان لتوريد الأسماك الطازجة والمجمدة</p></div><div class="doc-meta"><b>تاريخ الإصدار</b><span>${today()}</span><b>المستخدم</b><span>${esc(user.name)} — ${esc(user.title||'')}</span></div></div>`; }
function printInvoice(orderId,invId){ let inv=state.invoices.find(i=>i.id===invId)||state.invoices[0]||{}, ord=state.orders.find(o=>o.id===orderId)||state.orders.find(o=>o.customer===inv.customer)||state.orders[0]||{}; const items=(ord.items?.length?ord.items:[{product:'بند توريد أسماك',qty:1,price:inv.subtotal||ord.total||0}]); printPaper.innerHTML=`${printHeader('فاتورة بيع')}<div class="doc-box"><p><b>رقم الفاتورة:</b> ${esc(inv.id||'')}</p><p><b>العميل:</b> ${esc(inv.customer||ord.customer||'')}</p><p><b>التاريخ:</b> ${esc(inv.date||today())} — <b>الاستحقاق:</b> ${esc(inv.due||'')}</p></div><table class="doc-table"><tr><th>الصنف</th><th>الكمية</th><th>السعر</th><th>الإجمالي</th></tr>${items.map(x=>`<tr><td>${esc(x.product)}</td><td>${x.qty}</td><td>${fmt(x.price)}</td><td>${fmt(x.qty*x.price)}</td></tr>`).join('')}</table><div class="doc-total">الإجمالي: ${fmt(inv.subtotal||ord.total)} جنيه</div><div class="signs"><span>توقيع المستلم</span><span>توقيع الحسابات</span></div>`; window.print(); }
function printContract(id){ let c=state.contracts.find(x=>x.id===id)||state.contracts[0]||{}; printPaper.innerHTML=`${printHeader('عقد توريد')}<div class="contract-body"><p>تم الاتفاق بين شركة الإيمان لتوريد الأسماك وبين العميل <b>${esc(c.customer)}</b> على توريد المنتجات طبقاً للأسعار والجودة ومواعيد التسليم المتفق عليها.</p><p><b>مدة العقد:</b> من ${esc(c.start)} إلى ${esc(c.end)} — <b>الحالة:</b> ${esc(c.status)}</p><h3>بنود العقد</h3><p>${esc(c.terms)}</p><p>يلتزم الطرفان بالسداد، الجودة، آلية الاستلام، وأي ملاحظات تشغيلية يتم اعتمادها كتابياً.</p></div><div class="signs"><span>توقيع الشركة</span><span>توقيع العميل</span></div>`; window.print(); }
function dataFor(type){ if(type==='accounts') return [...state.receipts.map(x=>({نوع:'سند قبض',...x})),...state.expenses.map(x=>({نوع:'مصروف',...x}))]; if(type==='inventory') return state.products; if(type==='full') return [].concat(state.employees.map(x=>({Sheet:'Employees',...x})),state.customers.map(x=>({Sheet:'Customers',...x})),state.products.map(x=>({Sheet:'Products',...x})),state.invoices.map(x=>({Sheet:'Invoices',...x})),state.orders.map(x=>({Sheet:'Orders',...x}))); return state[type]||[]; }
function exportExcel(type){ const data=dataFor(type); const keys=[...new Set(data.flatMap(o=>Object.keys(o).filter(k=>k!=='avatar'&&k!=='items')))], rows=data.map(r=>`<tr>${keys.map(k=>`<td>${esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])}</td>`).join('')}</tr>`).join(''); const html=`<html dir="rtl"><head><meta charset="utf-8"><style>body{font-family:Tahoma;background:#f4f8fb}h1{background:#071b31;color:white;padding:20px;border-radius:16px}table{width:100%;border-collapse:collapse;background:white}th{background:#0878be;color:white;padding:10px}td{border:1px solid #dbe7f0;padding:9px}tr:nth-child(even){background:#eef7fd}.meta{color:#555}</style></head><body><h1>شركة الإيمان — تقرير ${type}</h1><p class="meta">تم التصدير بواسطة ${esc(user.name)} بتاريخ ${today()}</p><table><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr>${rows}</table></body></html>`; const blob=new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`al-eman-${type}-creative.xls`; a.click(); }
function resetData(){ if(confirm('سيتم حذف كل التعديلات والرجوع للبيانات الأصلية؟')){ localStorage.removeItem('aleman_state'); state=structuredClone(seed); save(); } }
function logout(){ localStorage.removeItem('aleman_user'); location.href='index.html'; }
init();
