
const state={user:JSON.parse(localStorage.getItem('aleman_user')||'null'),products:JSON.parse(localStorage.getItem('products')||'null')||PRICE_ITEMS.map(p=>({id:p[0],name:p[1],category:p[1].includes('جمبرى')?'جمبرى':p[1].includes('سالمون')?'سالمون':'مأكولات بحرية',price:p[2]||0,unit:'كجم',active:true})),customers:JSON.parse(localStorage.getItem('customers')||'null')||CUSTOMERS,orders:JSON.parse(localStorage.getItem('orders')||'[]'),deliveries:JSON.parse(localStorage.getItem('deliveries')||'[]'),invoices:JSON.parse(localStorage.getItem('invoices')||'[]'),contracts:JSON.parse(localStorage.getItem('contracts')||'[]'),complaints:JSON.parse(localStorage.getItem('complaints')||'[]'),employees:EMPLOYEES.map(e=>({role:e[0],title:e[1],name:e[2],email:e[3],password:e[4],permissions:e[5]}))};
if(!state.user) location.href='index.html';
const sections=[['dashboard','لوحة التحكم','all'],['customers','العملاء','customers'],['products','المنتجات والأسعار','products'],['orders','الطلبيات','orders'],['deliveries','التوصيل','deliveries'],['inventory','المخازن','inventory'],['invoices','الفواتير','invoices'],['contracts','العقود','contracts'],['complaints','الشكاوى','complaints'],['reports','التقارير','reports'],['employees','الموظفون','owner']];
function has(p){return state.user.permissions==='all'||state.user.permissions.includes(p)||(['owner','general_manager'].includes(state.user.role)&&p==='owner')}
function init(){roleName.textContent=state.user.title;userLabel.textContent=state.user.name;welcome.textContent=`أهلاً ${state.user.title} - نظام Realtime جاهز للربط مع Supabase`;sections.filter(s=>has(s[2])||s[0]==='dashboard').forEach((s,i)=>{const b=document.createElement('button');b.textContent=s[1];b.onclick=()=>show(s[0],s[1],b);if(i===0)b.classList.add('active');nav.appendChild(b)});renderAll();}
function show(id,title,btn){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');pageTitle.textContent=title;document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}
function save(){['products','customers','orders','deliveries','invoices','contracts','complaints'].forEach(k=>localStorage.setItem(k,JSON.stringify(state[k])));renderAll()}
function badge(v){let c=v==='active'||v==='تم التوصيل'||v==='مدفوعة'?'ok':v==='inactive'||v==='متأخر'?'danger':'warn';return `<span class="badge ${c}">${v||'جديد'}</span>`}
function renderAll(){kpiCustomers.textContent=state.customers.length;kpiProducts.textContent=state.products.length;kpiOrders.textContent=state.orders.length;kpiInvoices.textContent=state.invoices.length;alerts.innerHTML='<p>• يوجد عملاء بحاجة لمتابعة من فريق المبيعات.</p><p>• راجع أسعار الأصناف المتغيرة يومياً قبل التعاقد.</p>';renderCustomers();renderProducts();renderOrders();renderDeliveries();renderInventory();renderInvoices();renderContracts();renderComplaints();renderEmployees();buildPrintTemplates();}
function renderCustomers(){let q=(customerSearch?.value||'').toLowerCase();let rows=state.customers.filter(c=>(c.brand+c.phone+c.contact).toLowerCase().includes(q)).map((c,i)=>`<tr><td>${i+1}</td><td>${c.brand||''}</td><td>${c.phone||''}</td><td>${c.contact||''}</td><td>${c.location||''}</td><td>${c.sales||''}</td><td>${badge(c.status)}</td><td>${c.notes||''}</td></tr>`).join('');customersTable.innerHTML=`<tr><th>#</th><th>اسم البراند</th><th>رقم</th><th>المسؤول</th><th>الموقع</th><th>المبيعات</th><th>الحالة</th><th>ملاحظات</th></tr>${rows}`}
function renderProducts(){productsTable.innerHTML='<tr><th>#</th><th>الصنف</th><th>التصنيف</th><th>الوحدة</th><th>السعر</th><th>الحالة</th></tr>'+state.products.map(p=>`<tr><td>${p.id}</td><td>${p.name}</td><td>${p.category}</td><td>${p.unit}</td><td>${p.price.toLocaleString('en-US')}</td><td>${badge(p.active?'active':'inactive')}</td></tr>`).join('')}
function renderOrders(){ordersTable.innerHTML='<tr><th>رقم الطلب</th><th>العميل</th><th>الإجمالي</th><th>التسليم</th><th>المندوب</th><th>الحالة</th></tr>'+state.orders.map(o=>`<tr><td>${o.id}</td><td>${o.customer}</td><td>${o.total}</td><td>${o.date}</td><td>${o.driver}</td><td>${badge(o.status)}</td></tr>`).join('')}
function renderDeliveries(){deliveriesTable.innerHTML='<tr><th>الكود</th><th>العميل</th><th>المندوب</th><th>الموعد</th><th>الحالة</th></tr>'+state.deliveries.map(d=>`<tr><td>${d.id}</td><td>${d.customer}</td><td>${d.driver}</td><td>${d.date}</td><td>${badge(d.status)}</td></tr>`).join('')}
function renderInventory(){inventoryTable.innerHTML='<tr><th>الصنف</th><th>المخزن</th><th>الرصيد</th><th>حد التنبيه</th><th>الحالة</th></tr>'+state.products.slice(0,25).map((p,i)=>`<tr><td>${p.name}</td><td>المخزن الرئيسي</td><td>${120-i*3} كجم</td><td>20 كجم</td><td>${badge(i>20?'متأخر':'active')}</td></tr>`).join('')}
function renderInvoices(){invoicesTable.innerHTML='<tr><th>رقم</th><th>العميل</th><th>القيمة</th><th>التاريخ</th><th>الحالة</th><th>طباعة</th></tr>'+state.invoices.map(x=>`<tr><td>${x.id}</td><td>${x.customer}</td><td>${x.total}</td><td>${x.date}</td><td>${badge(x.status)}</td><td><button class="btn secondary" onclick="buildPrintTemplates();window.print()">طباعة</button></td></tr>`).join('')}
function renderContracts(){contractsTable.innerHTML='<tr><th>رقم</th><th>العميل</th><th>من</th><th>إلى</th><th>الحالة</th><th>طباعة</th></tr>'+state.contracts.map(x=>`<tr><td>${x.id}</td><td>${x.customer}</td><td>${x.start}</td><td>${x.end}</td><td>${badge(x.status)}</td><td><button class="btn secondary" onclick="buildPrintTemplates();window.print()">طباعة</button></td></tr>`).join('')}
function renderComplaints(){complaintsTable.innerHTML='<tr><th>رقم</th><th>العميل</th><th>الشكوى</th><th>المسؤول</th><th>الحالة</th></tr>'+state.complaints.map(x=>`<tr><td>${x.id}</td><td>${x.customer}</td><td>${x.text}</td><td>${x.owner}</td><td>${badge(x.status)}</td></tr>`).join('')}
function renderEmployees(){employeesTable.innerHTML='<tr><th>الوظيفة</th><th>الاسم</th><th>البريد</th><th>الصلاحيات</th></tr>'+state.employees.map(e=>`<tr><td>${e.title}</td><td>${e.name}</td><td>${e.email}</td><td>${e.permissions}</td></tr>`).join('')}
function modal(title,html){modalTitle.textContent=title;modalBody.innerHTML=html;document.getElementById('modal').classList.add('show')}function closeModal(){document.getElementById('modal').classList.remove('show')}
function openCustomerModal(){modal('إضافة عميل',`<div class="form-grid"><input class="input" id="mBrand" placeholder="اسم البراند"><input class="input" id="mPhone" placeholder="رقم الهاتف"><input class="input" id="mContact" placeholder="اسم المسؤول"><input class="input" id="mLocation" placeholder="الموقع"><textarea id="mNotes" placeholder="ملاحظات"></textarea></div><button class="btn" onclick="state.customers.unshift({brand:mBrand.value,phone:mPhone.value,contact:mContact.value,location:mLocation.value,sales:state.user.name,status:'lead',notes:mNotes.value});closeModal();save()">حفظ</button>`)}
function openProductModal(){modal('إضافة منتج',`<div class="form-grid"><input class="input" id="pName" placeholder="اسم الصنف"><input class="input" id="pCat" placeholder="التصنيف"><input class="input" id="pPrice" type="number" placeholder="السعر"><input class="input" id="pUnit" value="كجم"></div><button class="btn" onclick="state.products.push({id:state.products.length+1,name:pName.value,category:pCat.value,price:+pPrice.value,unit:pUnit.value,active:true});closeModal();save()">حفظ</button>`)}
function openOrderModal(){modal('طلب جديد',`<div class="form-grid"><input class="input" id="oCustomer" placeholder="العميل"><input class="input" id="oTotal" type="number" placeholder="الإجمالي"><input class="input" id="oDate" type="date"><input class="input" id="oDriver" placeholder="المندوب"></div><button class="btn" onclick="let id='ORD-'+Date.now().toString().slice(-6);state.orders.unshift({id,customer:oCustomer.value,total:+oTotal.value,date:oDate.value,driver:oDriver.value,status:'قيد التجهيز'});state.deliveries.unshift({id:'DEL-'+id,customer:oCustomer.value,driver:oDriver.value,date:oDate.value,status:'مجدول'});closeModal();save()">حفظ</button>`)}
function openInvoiceModal(){modal('فاتورة جديدة',`<div class="form-grid"><input class="input" id="iCustomer" placeholder="العميل"><input class="input" id="iTotal" type="number" placeholder="القيمة"><input class="input" id="iDate" type="date"><select id="iStatus"><option>غير مدفوعة</option><option>مدفوعة</option></select></div><button class="btn" onclick="state.invoices.unshift({id:'INV-'+Date.now().toString().slice(-6),customer:iCustomer.value,total:+iTotal.value,date:iDate.value,status:iStatus.value});closeModal();save()">حفظ</button>`)}
function openContractModal(){modal('عقد جديد',`<div class="form-grid"><input class="input" id="cCustomer" placeholder="العميل"><input class="input" id="cStart" type="date"><input class="input" id="cEnd" type="date"><input class="input" id="cStatus" value="ساري"></div><button class="btn" onclick="state.contracts.unshift({id:'CON-'+Date.now().toString().slice(-6),customer:cCustomer.value,start:cStart.value,end:cEnd.value,status:cStatus.value});closeModal();save()">حفظ</button>`)}
function openComplaintModal(){modal('إضافة شكوى',`<div class="form-grid"><input class="input" id="ccustomer" placeholder="العميل"><input class="input" id="cowner" placeholder="المسؤول"><textarea id="ctext" placeholder="تفاصيل الشكوى"></textarea></div><button class="btn" onclick="state.complaints.unshift({id:'CMP-'+Date.now().toString().slice(-6),customer:ccustomer.value,text:ctext.value,owner:cowner.value,status:'مفتوحة'});closeModal();save()">حفظ</button>`)}
function openEmployeeModal(){if(!['owner','general_manager'].includes(state.user.role))return alert('غير مسموح');modal('إضافة موظف',`<div class="form-grid"><input class="input" id="eName" placeholder="اسم الموظف"><input class="input" id="eEmail" placeholder="البريد"><input class="input" id="eTitle" placeholder="الوظيفة"><input class="input" id="ePerm" placeholder="الصلاحيات"></div><button class="btn" onclick="state.employees.push({title:eTitle.value,name:eName.value,email:eEmail.value,permissions:ePerm.value});closeModal();renderEmployees()">حفظ</button>`)}
function exportTable(name,rows){let html='<html><head><meta charset="utf-8"></head><body><table>'+rows+'</table></body></html>';let blob=new Blob([html],{type:'application/vnd.ms-excel'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.xls';a.click()}
function exportCustomersExcel(){exportTable('customers-aleman',customersTable.innerHTML)}function exportProductsExcel(){exportTable('price-list-aleman',productsTable.innerHTML)}
function buildPrintTemplates(){invoicePrint.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><img src="assets/logo.png" style="width:95px"><div><h1>فاتورة بيع</h1><p>شركة الإيمان لتوريد الأسماك الطازجة والمجمدة</p></div></div><hr><p><b>العميل:</b> ${state.invoices[0]?.customer||'................'}</p><p><b>التاريخ:</b> ${state.invoices[0]?.date||new Date().toISOString().slice(0,10)}</p><table><tr><th>الصنف</th><th>الكمية</th><th>السعر</th><th>الإجمالي</th></tr><tr><td>سالمون فيليه</td><td>10 كجم</td><td>900</td><td>9000</td></tr><tr><td>جمبرى لحم 30-26</td><td>5 كجم</td><td>950</td><td>4750</td></tr></table><h2>الإجمالي: ${state.invoices[0]?.total||13750} جنيه</h2><p>توقيع المستلم: .................... توقيع الحسابات: ....................</p>`;contractPrint.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><img src="assets/logo.png" style="width:95px"><h1>عقد توريد</h1></div><hr><p>إنه في يوم ${new Date().toLocaleDateString('ar-EG')} تم الاتفاق بين شركة الإيمان لتوريد الأسماك وبين العميل ${state.contracts[0]?.customer||'................'} على توريد منتجات الأسماك الطازجة والمجمدة طبقاً للأسعار والكميات المتفق عليها.</p><p><b>مدة العقد:</b> من ${state.contracts[0]?.start||'--'} إلى ${state.contracts[0]?.end||'--'}</p><p><b>بنود عامة:</b> الالتزام بمواعيد التسليم، جودة المنتج، وآلية السداد الموضحة بالفواتير.</p><br><p>توقيع الشركة: .................... توقيع العميل: ....................</p>`}
function printCurrent(id){buildPrintTemplates();window.print()}
function logout(){localStorage.removeItem('aleman_user');location.href='index.html'}
init();
