-- AL-EMAN ERP Supabase schema with Realtime
create extension if not exists "uuid-ossp";
create type app_role as enum ('owner','general_manager','sales_manager','sales_rep','delivery_manager','delivery_rep','accounts_manager','accountant','warehouse_manager','storekeeper','warehouse_staff');
create table if not exists profiles(id uuid primary key default uuid_generate_v4(), full_name text not null, email text unique, role app_role not null, is_active boolean default true, created_at timestamptz default now());
create table if not exists employees(id uuid primary key default uuid_generate_v4(), profile_id uuid references profiles(id), employee_code text unique, job_title text, department text, base_salary numeric default 0, allowances numeric default 0, deductions numeric default 0, hire_date date default current_date, status text default 'active');
create table if not exists attendance(id uuid primary key default uuid_generate_v4(), employee_id uuid references employees(id), day date not null, check_in time, check_out time, late_minutes int default 0, overtime_minutes int default 0, status text default 'present');
create table if not exists payroll(id uuid primary key default uuid_generate_v4(), employee_id uuid references employees(id), month date not null, base_salary numeric, allowances numeric default 0, deductions numeric default 0, net_salary numeric generated always as (base_salary + allowances - deductions) stored, status text default 'draft');
create table if not exists customers(id uuid primary key default uuid_generate_v4(), brand_name text not null, phone text, contact_name text, location text, address text, sales_owner uuid references profiles(id), status text default 'lead', notes text, created_at timestamptz default now());
create table if not exists products(id uuid primary key default uuid_generate_v4(), sku text unique, name text not null, category text, unit text default 'kg', current_price numeric default 0, is_active boolean default true);
create table if not exists price_history(id uuid primary key default uuid_generate_v4(), product_id uuid references products(id), old_price numeric, new_price numeric, effective_from date default current_date, changed_by uuid references profiles(id));
create table if not exists warehouses(id uuid primary key default uuid_generate_v4(), name text not null, location text, manager_id uuid references profiles(id));
create table if not exists inventory(id uuid primary key default uuid_generate_v4(), warehouse_id uuid references warehouses(id), product_id uuid references products(id), quantity numeric default 0, min_quantity numeric default 0, unique(warehouse_id,product_id));
create table if not exists inventory_movements(id uuid primary key default uuid_generate_v4(), warehouse_id uuid references warehouses(id), product_id uuid references products(id), movement_type text, quantity numeric, reason text, created_by uuid references profiles(id), created_at timestamptz default now());
create table if not exists orders(id uuid primary key default uuid_generate_v4(), order_no text unique, customer_id uuid references customers(id), sales_id uuid references profiles(id), delivery_date date, status text default 'draft', subtotal numeric default 0, discount numeric default 0, total numeric default 0, notes text, created_at timestamptz default now());
create table if not exists order_items(id uuid primary key default uuid_generate_v4(), order_id uuid references orders(id) on delete cascade, product_id uuid references products(id), quantity numeric, unit_price numeric, total numeric generated always as (quantity*unit_price) stored);
create table if not exists deliveries(id uuid primary key default uuid_generate_v4(), order_id uuid references orders(id), driver_id uuid references profiles(id), scheduled_at timestamptz, delivered_at timestamptz, status text default 'scheduled', proof_url text, notes text);
create table if not exists invoices(id uuid primary key default uuid_generate_v4(), invoice_no text unique, order_id uuid references orders(id), customer_id uuid references customers(id), issue_date date default current_date, due_date date, subtotal numeric default 0, discount numeric default 0, tax numeric default 0, total numeric default 0, paid numeric default 0, status text default 'unpaid');
create table if not exists payments(id uuid primary key default uuid_generate_v4(), invoice_id uuid references invoices(id), customer_id uuid references customers(id), amount numeric, method text, reference_no text, paid_at timestamptz default now(), notes text);
create table if not exists expenses(id uuid primary key default uuid_generate_v4(), expense_date date default current_date, category text, description text, amount numeric, status text default 'approved', created_by uuid references profiles(id));
create table if not exists contracts(id uuid primary key default uuid_generate_v4(), contract_no text unique, customer_id uuid references customers(id), start_date date, end_date date, terms text, status text default 'active', file_url text);
create table if not exists complaints(id uuid primary key default uuid_generate_v4(), customer_id uuid references customers(id), order_id uuid references orders(id), title text, details text, owner_id uuid references profiles(id), status text default 'open', created_at timestamptz default now());
create table if not exists audit_logs(id bigserial primary key, table_name text, record_id uuid, action text, changed_by uuid references profiles(id), payload jsonb, created_at timestamptz default now());
alter table profiles enable row level security; alter table employees enable row level security; alter table attendance enable row level security; alter table payroll enable row level security; alter table customers enable row level security; alter table products enable row level security; alter table price_history enable row level security; alter table warehouses enable row level security; alter table inventory enable row level security; alter table inventory_movements enable row level security; alter table orders enable row level security; alter table order_items enable row level security; alter table deliveries enable row level security; alter table invoices enable row level security; alter table payments enable row level security; alter table expenses enable row level security; alter table contracts enable row level security; alter table complaints enable row level security;
create policy "authenticated read" on products for select to authenticated using (true);
create policy "owner managers all profiles" on profiles for all to authenticated using (true) with check (true);
-- Realtime
alter publication supabase_realtime add table profiles, employees, attendance, payroll, customers, products, price_history, warehouses, inventory, inventory_movements, orders, order_items, deliveries, invoices, payments, expenses, contracts, complaints, audit_logs;
